apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ai
spec:
  version: v0.1.1
  homepage: https://github.com/helmcode/kubectl-ai
  shortDescription: AI-powered Kubernetes debugging
  description: |
    This plugin uses AI (Claude) to analyze Kubernetes resources and help debug
    configuration issues, performance problems, and provide actionable recommendations.

    Features:
    - Analyze any Kubernetes resource (native or CRD)
    - Get root cause analysis for issues
    - Receive actionable fix commands
    - Support for multiple output formats (human, json, yaml)

    Examples:
      # Debug a crashing deployment
      kubectl ai debug "pods are crashing" -r deployment/nginx

      # Analyze multiple resources
      kubectl ai debug "secrets not updating" -r deployment/vault -r vaultstaticsecret/creds

      # Debug all resources in a namespace
      kubectl ai debug "high memory usage" -n production --all
  caveats: |
    This plugin requires an Anthropic API key to function.

    Before using, set your API key:
      export ANTHROPIC_API_KEY="your-api-key"

    Get your API key at: https://console.anthropic.com/
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/helmcode/kubectl-ai/releases/download/v0.1.1/kubectl-ai-linux-amd64.tar.gz
    sha256: 9096ca657f775a3547f0ae474c6475bfec6e0e98d83266db9a61ad2b07bab877
    bin: kubectl-ai-linux-amd64
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/helmcode/kubectl-ai/releases/download/v0.1.1/kubectl-ai-linux-arm64.tar.gz
    sha256: 2341575f59db6b2aa6f7b8e8751c8a0c8031c1bcb08ee0ec5c9249a38e353cff
    bin: kubectl-ai-linux-arm64
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/helmcode/kubectl-ai/releases/download/v0.1.1/kubectl-ai-darwin-amd64.tar.gz
    sha256: c2bf3eb26b01280250766dac3bf3470065bda32440853381a8f8d20515fc4ac5
    bin: kubectl-ai-darwin-amd64
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/helmcode/kubectl-ai/releases/download/v0.1.1/kubectl-ai-darwin-arm64.tar.gz
    sha256: f2ccdfacd0a6c8c6b552e30a7747c6f326bbb06351d58cb2f8f43b8deb4a45db
    bin: kubectl-ai-darwin-arm64
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/helmcode/kubectl-ai/releases/download/v0.1.1/kubectl-ai-windows-amd64.exe.zip
    sha256: b84ac7bdf9961d6f7a39971791b06681a5336d34b98418e988eca8f6c1b5ee15
    bin: kubectl-ai.exe
